### ISSUE TITLE
"Not implemented" exception when trying to mock a query returning List<String>

### ISSUE THREAD

**Issue by R-J-Turner** [jmg48/NSubstitute.DbConnection#14]
When I try to mock a query which returns a List of String, this fails with the following message:

`Not yet implemented - if you need this method please raise a request on github :)`

The issue can be replicated by running "Test2" within the "UnitTest1" class of [the following repo](https://github.com/R-J-Turner/NSubstitute.DbConnection.Issue9/blob/main/NSubstitute.DbConnection.Issue9/UnitTest1.cs).

**Comment by jmg48** [comment]
Hi, thanks for raising this and for supplying an example to reproduce. I'll take a look into this and get back to you soon

   best wishes,
   Jon

**Comment by jmg48** [comment]
https://github.com/jmg48/NSubstitute.DbConnection/pull/15

**Comment by jmg48** [comment]
Should be fixed now in v.2.13 - https://www.nuget.org/packages/NSubstitute.Community.DbConnection/2.13.0

I'd be grateful if you would confirm and let me know if this is working for you now!

   thanks,
   Jon

**Comment by R-J-Turner** [comment]
Hi Jon,

I've upgraded, and can confirm that it has fixed the issue.

Thank you for the quick response, really appreciate it.

Thanks,
Rob
