### ISSUE TITLE
add link to package on nuget.org

### ISSUE THREAD

**Issue by atwayne** [jmg48/NSubstitute.DbConnection#6]
Hi,

Thanks for this great lib ;)
I tried search on https://www.nuget.org/ but found two matching packages, both looks legit but with different updated timestamp, could you specify in `README` which one is the official package you support?

- https://www.nuget.org/packages/NSubstitute.Community.DbConnection
- https://www.nuget.org/packages/DbConnection.NSubstitute

**Comment by jmg48** [comment]
Thanks for the suggestion - I've updated the readme, let me know if this works for you?
