### ISSUE TITLE
Unable to mock Dapper ExecuteScalarAsync queries

### ISSUE THREAD

**Issue by R-J-Turner** [jmg48/NSubstitute.DbConnection#9]
When I try to mock a call to Dapper's ExecuteScalarAsync method (or seemingly any other typed method returning a primitive type), it fails with:

`  System.Data.DataException : Error parsing column 0 (Id=<null>)
`

The code I'm using is as follows:

```
 IDbConnectionFactory connFactory = Substitute.For<IDbConnectionFactory>();
 DbConnection dbConn = Substitute.For<DbConnection>().SetupCommands();
 dbConn.SetupQuery(q => q.Contains("SELECT TOP 1")).Returns(new { Id = 1 });
 connFactory.GetConnection(default).ReturnsForAnyArgs(dbConn);
```

I inject the mock of IDbConnectionFactory into my class under test so that the returned DbConnection is the one I've mocked (which works fine in every other test case). I've tried a few return values (e.g. new [] { 1 }), but these do not work either. 

Code under test is:

```
 using(IDbConnection conn = _connectionFactory.GetConnection(_DbOptions.CurrentValue.ConnectionString))
 {
     if(conn.State != ConnectionState.Open)
         conn.Open();

     QueryBuilder q = conn.QueryBuilder(
         $@" SELECT TOP 1 Id
             FROM Foo
             WHERE Id = {id}
         )      
     ");

     bool exists = await q.ExecuteScalarAsync<bool>();
...
```
I've also tried calling other Dapper methods on the same query (i.e. Query, which returns nothing). The Dapper code works fine on the real database.

**Comment by jmg48** [comment]
Hello, have you tried mocking with a boolean value, i.e. `....Returns(new { Id = true });` in your example there?

Also can you list the package dependencies (and versions) you're using for this example, or ideally share a link to a working code sample I can run to repro this issue? Especially interested in the implementation of `conn.QueryBuilder()`

thanks, Jon

**Comment by R-J-Turner** [comment]
Hi Jon,

Thank you for taking a look into this. 

I tried your suggestion, but that doesn't seem to work either I'm afraid. 

I no longer seem to be getting the original error, but the call to ExecuteScalarAsync always returns null rather than true.

The QueryBuilder is a 3rd-party library (https://github.com/Drizin/DapperQueryBuilder), but I get the same issues if I just use vanilla Dapper.

I've uploaded a repo that I can replicate the issue in (https://github.com/R-J-Turner/NSubstitute.DbConnection.Issue9). Running the single unit test in the solution replicates the issue in vanilla Dapper and using the QueryBuilder.

Thanks,
Rob

**Comment by jmg48** [comment]
That's brilliant, thank you! I've got the issue reproduced and it looks like a simple enough fix in the end - the `ExecuteScalar()` methods hadn't been mocked so they need to be added alongside `ExecuteNonQuery()` and `ExecuteQuery()`

**Comment by jmg48** [comment]
Hi Rob, this functionality should be available now in v2.10.0 - let me know how you get on!

https://www.nuget.org/packages/NSubstitute.Community.DbConnection/2.10.0

best,
Jon

**Comment by R-J-Turner** [comment]
Hi Jon,

Thank you, this now works perfectly. Really appreciate the quick response. 

Have a nice weekend.

Cheers,
Rob

**Comment by jmg48** [comment]
No worries, thanks for raising this, and for providing a working repro of the issue - makes life very easy for me!
